---
title: "Schedule"
description: |
 Schedule and course materials for Data Science in R for Biologists (Zool 710 Spring 2023).
tbl-colwidths: [15,10, 55, 25]
---

## Schedule and course materials

For Qmd files (markdown document with [Quarto](https://quarto.org/docs/authoring/markdown-basics.html) which are cross-language executable code), go to the [course GitHub repository](https://github.com/mbutler808/mbutler808.github.io/) and navigate the directories, or best of all clone the repo and navigate within RStudio or your text browser and R console.


::: column-page
| Week         | Dates   | Topics                                                                                                                                                                                                                                                                                                 | Projects                                                                                                                                                                                                            |     |
|---------------|---------------|---------------|---------------|---------------|
| **Module 1** |         | **Computational Tools for Data Science** |||
||||||
| Week 1       | Jan 17  | `r emojifont::emoji('wave')` Installing R/RStudio, GitHub \[[html](posts/2023-01-17-the-big-picture/index.qmd)\] \[[Qmd](https://github.com/mbutler808/mbutler808.github.io/tree/main/posts/2023-01-17-the-big-picture/index.qmd)\]                                                                                                              |  ||
|              | Jan 19  | `r emojifont::emoji('woman_technologist')` Shell scripts, File Organization \[[html](posts/2023-01-19-your-computer-filesystems/index.qmd)\] \[[Qmd](https://github.com/mbutler808/mbutler808.github.io/tree/main/posts/2023-01-19-your-computer-filesystems/index.qmd)\] |||
||||||
| **Module 2** |         | **Data Analysis in R ** |||
||||||
| Week 2       | Jan 24 | `r emojifont::emoji('octopus')`  Intro to Git and GitHub \[[html](posts/2023-01-24-intro-git-github/index.qmd)\] \[[Qmd](https://github.com/mbutler808/mbutler808.github.io/tree/main/posts/2023-01-24-intro-git-github/index.qmd)\] |  `r emojifont::emoji('palm_tree')` Project 0 \[[html](projects/2023-01-24-project-0/index.qmd)\] \[[Qmd](https://github.com/mbutler808/mbutler808.github.io/blob/main/projects/2023-01-24-project-0/index.qmd)\]  | |
|        | Jan 24 | `r emojifont::emoji('octopus')` Reproducible Research and Literate Programming / Intro to Quarto |||
|              | Jan 26  | `r emojifont::emoji('microscope')` What is the Question? Data management and workflow  | | |
||||||
| Week 3       | Jan 31 | `r emojifont::emoji('eyeglasses')` Reading/Writing data | | |
|              | Feb 2 | `r emojifont::emoji('hocho')` Tidying Data  | `r emojifont::emoji('fallen_leaf')` Project 0 due ||
||||||
| **Module 3** |         | **Data Visulization in R** | | |
||||||
| Week 4       | Feb 7  | `r emojifont::emoji('bar_chart')` Plotting Systems (Base R)| | |
|              | Feb 9 | `r emojifont::emoji('bar_chart')` ggplot2 | | |
||||||
| **Module 4** |         | **Nuts and Bolts of R** |||
||||||
| Week 5       | Feb 14 | `r emojifont::emoji('nut_and_bolt')` R Nuts and Bolts (Objects) |||
|              | Feb 16 | `r emojifont::emoji('handshake')` Reshaping objects | `r emojifont::emoji('fallen_leaf')` Project 1 due |     |
||||||
| Week 6       | Feb 21 | `r emojifont::emoji('pencil')` Control Structures | | |
|              |  Feb 23 | `r emojifont::emoji('clipboard')` Functions | | |
||||||
|  Week 7       | Feb 28 | `r emojifont::emoji('monkey')` Loop Functions | |
||||||
|              | Mar 2  | `r emojifont::emoji('bug')`  Debugging and Error Handling |||
||||||
| **Module 5** |         | **Special Data Types** | | |
||||||
| Week 8       | Mar 7 | `r emojifont::emoji('calendar')` Dates and Times | | |
|              | Mar 9 | `r emojifont::emoji('racehorse')` Regular Expressions | `r emojifont::emoji('fallen_leaf')` Project 2 due | |
||||||
| Week 9       | Mar 14 | `r emojifont::emoji('sunny')` Spring Break |||
|              | Mar 16 | `r emojifont::emoji('sunny')` Spring Break |||
||||||
| Week 10      | Mar 21 | `r emojifont::emoji('mushroom')` Factors | | |
||||||
|              | Mar 23   | `r emojifont::emoji('cactus')` Text Data and Strings |  | |
||||||
| **Module 6** |         | **Intro to Morphometrics** | | |
||||||
| Week 11      | Mar 28   | `r emojifont::emoji('straight_ruler')` Linear Morphometrics, Size, Shape |||
||||||
|              | Mar 30  | `r emojifont::emoji('triangular_ruler')` Landmark-based Morphometrics |||
||||||
| Week 12      | Apr 4  | `r emojifont::emoji('skull')` 3D Morphometrics |||
|              | Apr 6  | `r emojifont::emoji('feet')` 3D Morphometrics |||
||||||
| **Module 7** |         | **Phylogenetic Trees** | | |
||||||
| Week 13      | Apr 11 | `r emojifont::emoji('seedling')` Trees as Data Objects | `r emojifont::emoji('fallen_leaf')` Project 3 due | |
|              | Apr 13  | `r emojifont::emoji('palm_tree')` Reading and writing trees, ape, ggtree, treeio |||
||||||
| Week 14      | Apr 18 | `r emojifont::emoji('deciduous_tree')` Reshaping Trees |||
||||||
|              | Apr 20 | `r emojifont::emoji('hibiscus')` Annotating Tree Plots |||
||||||
| **Module 8** |         | **Other Topics** | | |
||||||
| Week 15      | Apr 25  | `r emojifont::emoji('snake')` Parsing Data from any Format |||
||||||
|              | Apr 27  | `r emojifont::emoji('chestnut')` Student choice topic |||
||||||
|  Week 16     | May 2  | `r emojifont::emoji('trophy')` Final Presentations | `r emojifont::emoji('confetti_ball')` Project 4 due | |
||||||
:::
